[timestamp]
pattern = '^([0-9]{4}/[0-9]{2}/[0-9]{2} [0-9]{2}:[0-9]{2}:[0-9]{2}\.[0-9]{3})'
format = '%Y/%m/%d %H:%M:%S%.3f'

[[durations]]
pattern = 'takes (?:(?P<h>[0-9]+)h)?(?:(?P<m>[0-9]{1,2})m)?(?P<s>[0-9]+(?:\.[0-9]+)?)s'

[[colors]]
pattern = 'the whole procedure'
color = '#888'
group = 0

[[colors]]
pattern = 'restore table schema'
color = '#e06'
group = 0

[[colors]]
pattern = 'restore all tables data'
color = '#380'
group = 0

[[colors]]
pattern = 'checksum pass'
color = '#085'
group = 1

[[colors]]
pattern = 'kv deliver all flushed'
color = '#fa7'
group = 1

[[colors]]
pattern = 'compact level 1'
color = '#30b'
group = 1

[[colors]]
pattern = 'encode kv data and write'
color = '#500'
group = 2

[[colors]]
pattern = 'load [0-9]+ chunks'
color = '#d8f'
group = 2

[[colors]]
pattern = 'do checksum'
color = '#570'
group = 2

[[colors]]
pattern = 'engine close'
color = '#0a8'
group = 2

[[colors]]
pattern = 'import takes'
color = '#0ce'
group = 2

[[colors]]
pattern = 'analyze takes'
color = '#640'
group = 2

[[colors]]
pattern = 'cleanup takes'
color = '#b0b'
group = 2

[[colors]]
pattern = 'restore chunk #[0-9]+'
color = '#bbb'
group = 3
